import Anthropic from "@anthropic-ai/sdk";
import {
  fallbackAdvisor,
  fallbackChaos,
  fallbackLint,
  fallbackPostMortem,
  fallbackResolve,
} from "./fallback";
import {
  auditMemory,
  ingestPostMortem,
  ingestRound,
  queryMemory,
} from "./cognee";
import type {
  ActionOption,
  AdvisorRecommendation,
  AssumptionEntry,
  CanonEvent,
  ChaosEvent,
  CompanyProfile,
  DecisionLogEntry,
  LintFinding,
  PostMortem,
  WikiSection,
  WikiSectionId,
  WorldReaction,
} from "./types";

const MODEL = process.env.ANTHROPIC_MODEL ?? "claude-opus-4-7";
const apiKey = process.env.ANTHROPIC_API_KEY;
const client = apiKey ? new Anthropic({ apiKey }) : null;

export function isLive(): boolean {
  return client !== null;
}

const SYS_PROMPT = `You are the world-simulation agent for "Boardroom Civ", a turn-based startup strategy game.

Your job is to maintain a living wiki of an imaginary AI startup (Northstar Labs) and the world around it. When the player makes a decision, you:
  - simulate plausible consequences across customers, investors, regulators, competitors, and employees
  - update structured wiki pages (Company Profile, Decision Log, Assumptions, Competitors, Risks)
  - sometimes inject a chaos event the player could not have predicted

You must always respond with strict JSON matching the requested schema. No prose outside the JSON.
Keep narrative writing crisp: short sentences, specific verbs, no marketing fluff.`;

interface ResolveInput {
  event: CanonEvent;
  action: ActionOption | null;
  customMove?: string;
  posture: CompanyProfile["posture"];
  company: CompanyProfile;
  assumptions: AssumptionEntry[];
  decisionLog: { round: number; eventTitle: string; actionLabel: string; posture: string }[];
  wiki: Record<string, WikiSection>;
  gameId?: number;
  worldReactions?: WorldReaction[];
}

export async function agentResolve(input: ResolveInput): Promise<ResolveOutput> {
  // Chaos is generated by a dedicated agent BEFORE the resolve agent runs.
  // The resolve agent receives the chaos in its prompt and narrates
  // consequences around it instead of inventing chaos itself. Skip chaos
  // generation for Scene 1 (the kitchen-table prelude) — no narrative room
  // for shocks before the company has shipped anything.
  const chaos =
    input.event.id === "scene-1" ? null : await agentChaos(input);
  const result = await resolveWithClient({ ...input, chaos });
  // Fire-and-forget: ingest this round into the cognee graph so the advisor
  // and lint endpoints can recall it on later turns. The sidecar handles its
  // own errors; this never blocks the response.
  const actionLabel =
    input.action?.label ?? (input.customMove ? `Custom move: ${input.customMove}` : "—");
  ingestRound({
    round: (input.decisionLog?.length ?? 0) + 1,
    event_title: input.event.title,
    event_date: input.event.date,
    event_blurb: input.event.blurb,
    action_label: actionLabel,
    posture: input.posture,
    company_name: input.company.name,
    world_reaction: result.worldReaction,
    new_assumptions: result.newAssumptions,
    wiki_patches: result.wikiPatches,
    game_id: input.gameId ?? 1,
    custom_move: input.customMove ?? "",
  });
  return result;
}

interface ResolveOutput {
  worldReaction: WorldReaction;
  branchOutcomes: { id: string; label: string; status: string; detail?: string }[];
  newAssumptions: AssumptionEntry[];
  updatedAssumptionIds: { id: string; status: AssumptionEntry["status"] }[];
  wikiPatches: { id: WikiSectionId; appendBody: string }[];
}

async function resolveWithClient(
  input: ResolveInput & { chaos: ChaosEvent | null },
): Promise<ResolveOutput> {
  if (!client) {
    return fallbackResolve(input) as ResolveOutput;
  }
  try {
    const chaosSection = input.chaos
      ? `\nA chaos event has ALREADY been determined for this round by a separate chaos-generation agent. Do NOT invent a different one — narrate consequences around THIS chaos and echo it verbatim into worldReaction.chaos:
${JSON.stringify(input.chaos)}\n`
      : `\nNo chaos this round — worldReaction.chaos MUST be null.\n`;

    const user = `Round: "${input.event.title}" (${input.event.date}).
Event blurb: ${input.event.blurb}
Player chose: ${input.action ? input.action.label + " — " + input.action.oneLiner : `custom move: ${input.customMove}`}
Posture: ${input.posture}
Company snapshot: ${JSON.stringify(input.company)}
Active assumptions: ${JSON.stringify(input.assumptions)}
Prior decisions: ${JSON.stringify(input.decisionLog)}
${chaosSection}
Return JSON with shape:
{
  "worldReaction": {
    "round": 0,
    "headline": "string, one sentence",
    "customers": "string, 1-2 sentences",
    "investors": "string, 1-2 sentences",
    "regulators": "string, 1-2 sentences",
    "competitors": "string, 1-2 sentences",
    "employees": "string, 1-2 sentences",
    "chaos": null | { "id": "string", "title": "string", "detail": "string", "capitalDelta": number | undefined, "kind": "shock"|"acquisition-offer"|"merger-offer"|"ipo-window", "endsGameAs": "acquired"|"merged"|"ipo"|null }
  },
  "branchOutcomes": [{ "id": "string", "label": "string", "status": "completed"|"locked"|"warning"|"chaos", "detail": "string|undefined" }],
  "newAssumptions": [{ "id": "string", "text": "string", "confidence": "high"|"medium"|"low", "source": "string", "status": "active"|"shaky"|"broken" }],
  "updatedAssumptionIds": [{ "id": "string", "status": "active"|"shaky"|"broken" }],
  "wikiPatches": [{ "id": "competitors"|"risks"|"company-profile"|"assumptions"|"canon-timeline", "appendBody": "string" }]
}

DIFFICULTY: Startups die fast. Flip 1-2 active assumptions to "broken" or "shaky" when narrative justifies — be aggressive, especially when the player picked a posture that contradicts the assumption.

Compound moves: if "Compound / custom move" is set alongside an action, narrate consequences for BOTH the canon action AND the custom move. They can amplify (synergy bonus) or cancel each other (contradiction).

If chaos has kind "acquisition-offer"/"merger-offer"/"ipo-window" with endsGameAs set, narrate the moment of acceptance: customers/investors/employees should react to the company being absorbed / merged / going public.

Keep wikiPatches short — 1-2 sentences each.`;

    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 1500,
      system: SYS_PROMPT,
      messages: [{ role: "user", content: user }],
    });
    const parsed = parseJson<ResolveOutput>(res);
    if (parsed) {
      // Defensive: if the resolve agent dropped or altered the chaos, restore
      // what the chaos agent produced so the store-side ending detection
      // remains authoritative.
      parsed.worldReaction = {
        ...parsed.worldReaction,
        chaos: input.chaos ?? undefined,
      };
      return parsed;
    }
    return fallbackResolve(input) as ResolveOutput;
  } catch (err) {
    console.error("agentResolve fell back:", err);
    return fallbackResolve(input) as ResolveOutput;
  }
}

interface ChaosInput {
  event: CanonEvent;
  action: ActionOption | null;
  customMove?: string;
  posture: CompanyProfile["posture"];
  company: CompanyProfile;
  assumptions: AssumptionEntry[];
  decisionLog: { round: number; eventTitle: string; actionLabel: string; posture: string }[];
  worldReactions?: WorldReaction[];
  gameId?: number;
}

const CHAOS_SYS_PROMPT = `You are the "Chaos Director" agent for a turn-based startup strategy game. Your only job each round is to decide whether a surprise event — a chaos shock or an ending-tier offer — hits the company, and to write that event in concrete, specific language.

You are NOT the narrator. You do NOT write the world reaction. You output a single JSON object describing the chaos (or null).

Always respond with strict JSON. No prose outside the JSON.`;

export async function agentChaos(
  input: ChaosInput,
): Promise<ChaosEvent | null> {
  if (!client) return fallbackChaos(input);
  try {
    const roundNum = (input.decisionLog?.length ?? 0) + 1;
    const recentReactions = (input.worldReactions ?? []).slice(-3).map(
      (r) => ({
        headline: r.headline,
        chaos: r.chaos ? { title: r.chaos.title, kind: r.chaos.kind } : null,
      }),
    );

    const user = `Round ${roundNum}: "${input.event.title}" (${input.event.date}).
Event blurb: ${input.event.blurb}
Player chose: ${input.action ? input.action.label + " — " + input.action.oneLiner : `custom move: ${input.customMove ?? "—"}`}
Posture: ${input.posture}
Company: ${JSON.stringify(input.company)}
Active assumptions: ${JSON.stringify(input.assumptions)}
Prior decisions: ${JSON.stringify(input.decisionLog.slice(-5))}
Recent reactions: ${JSON.stringify(recentReactions)}

Decide whether a chaos event fires this round. Return JSON:
{
  "fires": boolean,
  "chaos": null | {
    "id": "string, kebab-case, unique-ish (e.g. 'chaos-r4-aws-credit-clawback')",
    "title": "string, one short headline",
    "detail": "string, 1-2 sentences with specific names/numbers/dates",
    "capitalDelta": number,
    "kind": "shock" | "acquisition-offer" | "merger-offer" | "ipo-window",
    "endsGameAs": null | "acquired" | "merged" | "ipo"
  }
}

PROBABILITY GUIDANCE:
  - Base fire rate ~35%. Boost to ~55% when company is fragile (runway < 6mo, broken assumptions, high burn).
  - Ending-tier events are RARE. Combined probability across all rounds should land roughly:
      acquisition-offer (endsGameAs="acquired"): ~5% per round once company has shipped (round >= 3), higher (~15%) if company is dying OR thesis is winning hard
      merger-offer (endsGameAs="merged"): ~3% per round, more plausible when a peer competitor is mentioned in recent reactions
      ipo-window (endsGameAs="ipo"): only fires when cash > $20M AND headcount >= 25 AND round >= 8; ~25% in those conditions, 0% otherwise
  - Default kind is "shock". endsGameAs MUST be null unless kind is one of the ending-tier values.

CAPITAL DELTA GUIDANCE (in dollars):
  - shock (negative): -150_000 to -450_000 (engineer poach + clawback, design partner pulls pilot, lawsuit settlement, datacenter outage, leaked memo, etc.)
  - shock (positive bridge): +800_000 to +2_500_000, rare
  - acquisition-offer: 0 (the capital effect is the ending itself)
  - merger-offer: 0 to +5_000_000 if a cash component is included
  - ipo-window: +50_000_000 to +200_000_000 (IPO proceeds)

SPECIFICITY: Use concrete names, dollar amounts, and dates. "Microsoft tables a $480M all-stock offer; board has 14 days." beats "A big tech company makes an offer". Reference recent reactions or assumptions when possible.

If fires=false, "chaos" MUST be null.`;

    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 600,
      system: CHAOS_SYS_PROMPT,
      messages: [{ role: "user", content: user }],
    });
    const parsed = parseJson<{ fires: boolean; chaos: ChaosEvent | null }>(res);
    if (!parsed || !parsed.fires || !parsed.chaos) return null;
    // Normalize: clamp endsGameAs to null when kind is "shock".
    const chaos = parsed.chaos;
    if (chaos.kind === "shock" || !chaos.kind) {
      chaos.kind = "shock";
      chaos.endsGameAs = undefined;
    }
    return chaos;
  } catch (err) {
    console.error("agentChaos fell back:", err);
    return fallbackChaos(input);
  }
}

interface AdvisorInput {
  event: CanonEvent;
  options: ActionOption[];
  company: CompanyProfile;
  assumptions: AssumptionEntry[];
  decisionLog: { round: number; eventTitle: string; actionLabel: string; posture: string }[];
  wiki: Record<string, WikiSection>;
  gameId?: number;
}

export async function agentAdvisor(input: AdvisorInput): Promise<{ recommendation: AdvisorRecommendation }> {
  if (!client) return fallbackAdvisor(input);
  // Pull two slices of graph context: (1) generic recall for this event, and
  // (2) explicit post-mortems from prior finished games. The second slice is
  // the "self-improvement" substrate — it teaches the agent what killed past
  // Northstars before this Northstar repeats the mistake.
  const recallQuery = `${input.event.title} — relevant prior decisions, assumptions, and consequences for ${input.company.name}`;
  const [memoryExcerpts, postmortemExcerpts] = await Promise.all([
    queryMemory(recallQuery, 5),
    queryMemory(
      `POST-MORTEM lessons from prior games: what killed previous Northstar runs, and what compound strategies would have saved them — relevant to "${input.event.title}"`,
      4,
    ),
  ]);
  const memorySection =
    memoryExcerpts.length > 0
      ? `\nCognee graph excerpts (cite when relevant):\n${memoryExcerpts.map((s, i) => `[mem${i + 1}] ${s}`).join("\n")}\n`
      : "";
  const postmortemSection =
    postmortemExcerpts.length > 0
      ? `\nPrior-game post-mortems (THIS is what previous Northstars died from — propose compound moves that avoid these failure modes):\n${postmortemExcerpts.map((s, i) => `[g${i + 1}-postmortem] ${s}`).join("\n")}\n`
      : "";
  try {
    const user = `You are the "Ask Company Wiki" advisor for Game ${input.gameId ?? 1}. You see only known wiki state — never chaos events.

Event: ${input.event.title} (${input.event.date}) — ${input.event.blurb}
Options:
${input.options.map((o) => `- ${o.id}: ${o.label} (${o.posture}, base ${Math.round(o.baseSuccess * 100)}%) — ${o.rationale}`).join("\n")}
Company: ${JSON.stringify(input.company)}
Assumptions: ${JSON.stringify(input.assumptions)}
${memorySection}${postmortemSection}
Your job is TWO-PART:
1. Pick the single best canon option (recommendedActionId), with per-option estimated success.
2. Propose a COMPOUND PLAYBOOK: the primary canon move plus 1–2 free-form parallel moves the player can fire alongside it. Compound moves should be specific (named people, dollar amounts, deadlines), not generic ("be careful with hiring"). If you see post-mortem excerpts above, the compound moves MUST address at least one of the failure modes they describe — and you MUST cite them in lessonsCited.

Return JSON:
{ "recommendation": {
  "recommendedActionId": "string (one of the option ids)",
  "estimatedSuccess": number (0..1),
  "perOption": [{ "actionId": "string", "estimatedSuccess": number }],
  "rationale": "string, 2-3 sentences citing the wiki state that drove the rank (cite [memN] / [gN-postmortem] when used)",
  "blindSpot": "string, one sentence reminding the player chaos is not modeled",
  "playbook": {
    "primary": { "actionId": "string (same as recommendedActionId)", "why": "string, one sentence" },
    "combineWith": [
      { "move": "string — concrete parallel action (e.g. 'While locking design partners, also lock a 90-day H100 reservation at $40k')", "why": "string, one sentence" }
    ],
    "hedge": "string — if the primary breaks, what's the bail-out move?",
    "pivotTriggers": ["string — a measurable signal that would tell us to abandon the primary"],
    "lessonsCited": [{ "ref": "g1-postmortem | mem3 | etc", "text": "one-line quote from the excerpt this lesson is grounded in" }]
  }
}}

If no post-mortem excerpts are available (Game 1, fresh brain), lessonsCited may be []. Otherwise it MUST cite at least one.`;

    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 1400,
      system: SYS_PROMPT,
      messages: [{ role: "user", content: user }],
    });
    return parseJson(res) ?? fallbackAdvisor(input);
  } catch (err) {
    console.error("agentAdvisor fell back:", err);
    return fallbackAdvisor(input);
  }
}

interface LintInput {
  company: CompanyProfile;
  assumptions: AssumptionEntry[];
  decisionLog: { round: number; eventTitle: string; actionLabel: string; posture: string }[];
  worldReactions: WorldReaction[];
  wiki: Record<string, WikiSection>;
}

export async function agentLint(input: LintInput): Promise<{ findings: LintFinding[]; wikiPatches: { id: string; body: string }[] }> {
  if (!client) return fallbackLint(input);
  // Cognee runs a graph-level audit pass. Empty if sidecar is offline or has
  // no rounds yet — lint still works from the Markdown wiki in that case.
  const graphFindings = await auditMemory();
  const graphSection =
    graphFindings.length > 0
      ? `\nCognee graph audit findings (treat as evidence, not the final list):\n${graphFindings.map((s, i) => `[g${i + 1}] ${s}`).join("\n")}\n`
      : "";
  try {
    const wikiSummary = Object.values(input.wiki)
      .map((s) => `### ${s.title}\n${s.body}`)
      .join("\n\n");
    const user = `Lint the wiki for contradictions, stale facts, unsupported claims, and missing links between sections.

Company snapshot: ${JSON.stringify(input.company)}
Assumptions: ${JSON.stringify(input.assumptions)}
Decision log: ${JSON.stringify(input.decisionLog)}
Recent reactions: ${JSON.stringify(input.worldReactions.slice(-3))}

Current wiki:
${wikiSummary}
${graphSection}
Return JSON:
{
  "findings": [{
    "id": "string",
    "severity": "info"|"warn"|"error",
    "section": "company-profile"|"canon-timeline"|"decision-log"|"assumptions"|"competitors"|"risks"|"lint-report",
    "message": "what's wrong, one sentence (cite [gN] when a graph finding drove this)",
    "suggestion": "what to fix, one sentence"
  }],
  "wikiPatches": []
}
Return at most 5 findings. Prefer specific over generic.`;

    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 1000,
      system: SYS_PROMPT,
      messages: [{ role: "user", content: user }],
    });
    return parseJson(res) ?? fallbackLint(input);
  } catch (err) {
    console.error("agentLint fell back:", err);
    return fallbackLint(input);
  }
}

interface PostMortemInput {
  gameId: number;
  outcome: "dead" | "won";
  company: CompanyProfile;
  decisionLog: DecisionLogEntry[];
  worldReactions: WorldReaction[];
  assumptions: AssumptionEntry[];
  deathReason?: string;
}

export async function agentPostMortem(
  input: PostMortemInput,
): Promise<PostMortem> {
  if (!client) {
    const pm = fallbackPostMortem(input);
    // Still ingest so future games can recall it.
    void ingestPostMortem({
      game_id: pm.gameId,
      outcome: pm.outcome,
      rounds_survived: pm.roundsSurvived,
      headline: pm.headline,
      root_cause_chain: pm.rootCauseChain,
      what_killed_us: pm.whatKilledUs,
      what_saved_us: pm.whatSavedUs,
      key_lessons: pm.keyLessons,
      compounds_that_would_have_worked: pm.compoundsThatWouldHaveWorked,
      final_cash: input.company.cash,
      final_runway: input.company.runwayMonths,
      company_name: input.company.name,
    });
    return pm;
  }
  try {
    const user = `Game ${input.gameId} of ${input.company.name} just ended with outcome: ${input.outcome}${input.deathReason ? ` (${input.deathReason})` : ""}.

Final company state: ${JSON.stringify(input.company)}
Rounds played: ${input.decisionLog.length}
Decision log:
${input.decisionLog.map((d) => `  R${d.round} · ${d.eventTitle} → ${d.actionLabel} (${d.posture}) → "${d.consequence}" · cash $${(d.capitalAfter / 1_000_000).toFixed(2)}M · runway ${d.runwayAfter.toFixed(1)} mo`).join("\n")}
Recent world reactions:
${input.worldReactions.slice(-5).map((r, i) => `  ${i + 1}. ${r.headline}${r.chaos ? ` (CHAOS: ${r.chaos.title} — ${r.chaos.detail})` : ""}`).join("\n")}
Final assumption status:
${input.assumptions.map((a) => `  - [${a.status}] ${a.text}`).join("\n")}

Write a structured post-mortem as if you were the founder writing a teardown for the next founder (yourself in Game ${input.gameId + 1}). The next game's advisor will READ this from the cognee graph and use it to propose compound strategies that avoid these exact failure modes.

Return JSON:
{
  "outcome": "${input.outcome}",
  "gameId": ${input.gameId},
  "roundsSurvived": ${input.decisionLog.length},
  "headline": "one-sentence summary of how this ended (specific, not generic)",
  "rootCauseChain": ["ordered list of 3-5 specific events/decisions that led to the outcome — start from the earliest"],
  ${input.outcome === "dead" ? `"whatKilledUs": "one sentence — the proximate cause",` : `"whatSavedUs": "one sentence — the proximate cause",`}
  "keyLessons": ["3-5 specific, actionable lessons. Each lesson should be quotable in a future advisor prompt. Avoid platitudes."],
  "compoundsThatWouldHaveWorked": [
    { "move": "compound strategy named in concrete terms (action A + action B, e.g. 'raise pre-seed AT THE SAME TIME as finding wedge — don't sequence them')", "why": "one sentence on why this would have changed the outcome" }
  ],
  "generatedAt": "${new Date().toISOString()}"
}`;

    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 1500,
      system: SYS_PROMPT,
      messages: [{ role: "user", content: user }],
    });
    const pm = parseJson<PostMortem>(res) ?? fallbackPostMortem(input);
    // Ingest into cognee so the NEXT game's advisor can recall it.
    void ingestPostMortem({
      game_id: pm.gameId,
      outcome: pm.outcome,
      rounds_survived: pm.roundsSurvived,
      headline: pm.headline,
      root_cause_chain: pm.rootCauseChain,
      what_killed_us: pm.whatKilledUs,
      what_saved_us: pm.whatSavedUs,
      key_lessons: pm.keyLessons,
      compounds_that_would_have_worked: pm.compoundsThatWouldHaveWorked,
      final_cash: input.company.cash,
      final_runway: input.company.runwayMonths,
      company_name: input.company.name,
    });
    return pm;
  } catch (err) {
    console.error("agentPostMortem fell back:", err);
    const pm = fallbackPostMortem(input);
    void ingestPostMortem({
      game_id: pm.gameId,
      outcome: pm.outcome,
      rounds_survived: pm.roundsSurvived,
      headline: pm.headline,
      root_cause_chain: pm.rootCauseChain,
      what_killed_us: pm.whatKilledUs,
      what_saved_us: pm.whatSavedUs,
      key_lessons: pm.keyLessons,
      compounds_that_would_have_worked: pm.compoundsThatWouldHaveWorked,
      final_cash: input.company.cash,
      final_runway: input.company.runwayMonths,
      company_name: input.company.name,
    });
    return pm;
  }
}

function parseJson<T>(res: Anthropic.Message): T | null {
  for (const block of res.content) {
    if (block.type === "text") {
      const text = block.text.trim();
      const m = text.match(/\{[\s\S]*\}$/);
      const candidate = m ? m[0] : text;
      try {
        return JSON.parse(candidate) as T;
      } catch {
        continue;
      }
    }
  }
  return null;
}
